site_name: PyVisionAI
site_url: https://pyvisionai.dev
site_description: Advanced document content processing using Vision Language Models
site_author: PyVisionAI Team

# Social/SEO metadata
repo_url: https://github.com/MDGrey33/pyvisionai
repo_name: MDGrey33/pyvisionai
edit_uri: edit/main/docs/

# OpenGraph metadata
og_title: PyVisionAI Documentation
og_description: Advanced document content processing using Vision Language Models (VLMs)
og_image: assets/images/visual.jpeg
og_url: https://pyvisionai.dev

# Twitter metadata
twitter_site: pyvisionai
twitter_creator: pyvisionai
twitter_card: summary_large_image
twitter_image: assets/images/visual.jpeg

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.jpeg
  favicon: assets/images/favicon.jpeg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - announce.dismiss
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Documentation: 
    - Getting Started: documentation/getting-started.md
    - Installation: documentation/installation.md
    - Usage: documentation/usage.md
  - Community: community.md
  - Resources: resources.md
  - Contact: contact.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MDGrey33/pyvisionai
      name: PyVisionAI on GitHub
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyvisionai/
      name: PyVisionAI on PyPI
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  version:
    provider: mike
    default: latest
  social_cards: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: Copyright &copy; 2024 PyVisionAI Team
